/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Search;

import Data.Dish;
import Data.Menu;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bhárbara
 */
public class SearchJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchJFrame
     */
    public SearchJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisarNomeSearch = new javax.swing.JTextField();
        lblPesquisarNomeSearch = new javax.swing.JLabel();
        btnPesquisarSearch = new javax.swing.JButton();
        txtPesquisarChaveSearch = new javax.swing.JTextField();
        lblPesquisarChaveSearch = new javax.swing.JLabel();
        lblPesquisarAtributosSearch = new javax.swing.JLabel();
        comboGlutenSearch = new javax.swing.JComboBox();
        comboVegetarianoSearch = new javax.swing.JComboBox();
        comboVeganoSearch = new javax.swing.JComboBox();
        comboLactoseSearch = new javax.swing.JComboBox();
        lblPesquisarTipoSearch = new javax.swing.JLabel();
        txtPesquisarTipoSearch = new javax.swing.JTextField();
        lblPesquisarDescontoSearch = new javax.swing.JLabel();
        txtPesquisarDescontoSearch = new javax.swing.JTextField();
        lblPesquisarPrecoSearch = new javax.swing.JLabel();
        txtPesquisarPrecoSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPesquisarNomeSearch.setText("Procura por Nome:");

        btnPesquisarSearch.setText("Pesquisar");
        btnPesquisarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSearchActionPerformed(evt);
            }
        });

        txtPesquisarChaveSearch.setToolTipText("Separar palavras-chave por vírgulas");

        lblPesquisarChaveSearch.setText("Pesquisar palavras-chave:");

        lblPesquisarAtributosSearch.setText("Pesquisar por atributo:");

        comboGlutenSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gluten", "Sim", "Não" }));

        comboVegetarianoSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vegetariano", "Sim", "Não" }));

        comboVeganoSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vegano", "Sim", "Não" }));

        comboLactoseSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lactose", "Sim", "Não" }));

        lblPesquisarTipoSearch.setText("Pesquisar por Tipo:");

        lblPesquisarDescontoSearch.setText("Pesquisar por Desconto:");

        lblPesquisarPrecoSearch.setText("Procurar por Preço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisarPrecoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarDescontoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarPrecoSearch)
                    .addComponent(lblPesquisarDescontoSearch)
                    .addComponent(txtPesquisarTipoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarTipoSearch)
                    .addComponent(txtPesquisarChaveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarChaveSearch)
                    .addComponent(txtPesquisarNomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarNomeSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisarAtributosSearch)
                    .addComponent(comboGlutenSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVeganoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVegetarianoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLactoseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarNomeSearch)
                    .addComponent(lblPesquisarAtributosSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarNomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGlutenSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisarChaveSearch)
                    .addComponent(comboVeganoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarChaveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVegetarianoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLactoseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarTipoSearch))
                .addGap(8, 8, 8)
                .addComponent(txtPesquisarTipoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPesquisarDescontoSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPesquisarDescontoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisarPrecoSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPesquisarPrecoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisarSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSearchActionPerformed
        Menu menu = new Menu();
        DefaultListModel temp = new DefaultListModel();
        for(Dish d: menu.getDishes()){
            if(!(txtPesquisarNomeSearch.getText().equals(""))){
                if(d.getName().equalsIgnoreCase(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            if(!(txtPesquisarChaveSearch.getText().equals(""))){
                if(d.getDescription().contains(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            
            if(!(txtPesquisarTipoSearch.getText().equals(""))){
                if(d.getType().equalsIgnoreCase(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            if(!(txtPesquisarDescontoSearch.getText().equals(""))){
                if(d.getDiscount() == Float.parseFloat(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            if(!(txtPesquisarNomeSearch.getText().equals(""))){
                if(d.getPrice() == Float.parseFloat(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            
        }
    }//GEN-LAST:event_btnPesquisarSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarSearch;
    private javax.swing.JComboBox comboGlutenSearch;
    private javax.swing.JComboBox comboLactoseSearch;
    private javax.swing.JComboBox comboVeganoSearch;
    private javax.swing.JComboBox comboVegetarianoSearch;
    private javax.swing.JLabel lblPesquisarAtributosSearch;
    private javax.swing.JLabel lblPesquisarChaveSearch;
    private javax.swing.JLabel lblPesquisarDescontoSearch;
    private javax.swing.JLabel lblPesquisarNomeSearch;
    private javax.swing.JLabel lblPesquisarPrecoSearch;
    private javax.swing.JLabel lblPesquisarTipoSearch;
    private javax.swing.JTextField txtPesquisarChaveSearch;
    private javax.swing.JTextField txtPesquisarDescontoSearch;
    private javax.swing.JTextField txtPesquisarNomeSearch;
    private javax.swing.JTextField txtPesquisarPrecoSearch;
    private javax.swing.JTextField txtPesquisarTipoSearch;
    // End of variables declaration//GEN-END:variables
}
