/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Search;

import Data.Dish;
import Data.Menu;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Bhárbara
 */
public class SearchJFrame extends javax.swing.JFrame {

    private DefaultListModel temp;
    
    /**
     * Creates new form SearchJFrame
     * @param list the list to be searched
     */
    public SearchJFrame() {
        initComponents();
        temp = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtPesquisarNomeSearch = new javax.swing.JTextField();
        lblPesquisarNomeSearch = new javax.swing.JLabel();
        btnPesquisarSearch = new javax.swing.JButton();
        txtPesquisarChaveSearch = new javax.swing.JTextField();
        lblPesquisarChaveSearch = new javax.swing.JLabel();
        lblPesquisarAtributosSearch = new javax.swing.JLabel();
        lblPesquisarTipoSearch = new javax.swing.JLabel();
        txtPesquisarTipoSearch = new javax.swing.JTextField();
        lblPesquisarDescontoSearch = new javax.swing.JLabel();
        txtPesquisarDescontoSearch = new javax.swing.JTextField();
        lblPesquisarPrecoSearch = new javax.swing.JLabel();
        txtPesquisarPrecoSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPesquisarNomeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarNomeSearchActionPerformed(evt);
            }
        });

        lblPesquisarNomeSearch.setText("Procura por Nome:");

        btnPesquisarSearch.setText("Pesquisar");
        btnPesquisarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSearchActionPerformed(evt);
            }
        });

        txtPesquisarChaveSearch.setToolTipText("Separar palavras-chave por vírgulas");

        lblPesquisarChaveSearch.setText("Pesquisar palavras-chave:");

        lblPesquisarAtributosSearch.setText("Pesquisar por atributo:");

        lblPesquisarTipoSearch.setText("Pesquisar por Tipo:");

        lblPesquisarDescontoSearch.setText("Pesquisar por Desconto:");

        lblPesquisarPrecoSearch.setText("Procurar por Preço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pesquisa no Menu");

        jCheckBox1.setText("Glúten");

        jCheckBox2.setText("Vegan");

        jCheckBox3.setText("Vegetariano");

        jCheckBox4.setText("Lactose");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPesquisarNomeSearch)
                                    .addComponent(txtPesquisarDescontoSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtPesquisarNomeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(lblPesquisarDescontoSearch)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4))
                                .addComponent(lblPesquisarChaveSearch)
                                .addComponent(lblPesquisarAtributosSearch))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPesquisarTipoSearch)
                                .addComponent(txtPesquisarTipoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPesquisarPrecoSearch)
                                .addComponent(txtPesquisarPrecoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtPesquisarChaveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox4)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnPesquisarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarNomeSearch)
                    .addComponent(lblPesquisarTipoSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarNomeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarTipoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesquisarChaveSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarChaveSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarDescontoSearch)
                    .addComponent(lblPesquisarPrecoSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarDescontoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarPrecoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesquisarAtributosSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSearchActionPerformed
        Menu menu = new Menu();
        for(Dish d: menu.getDishes()){
            try{
                if(d.getName().equalsIgnoreCase(txtPesquisarNomeSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }                
            }
            catch(NullPointerException npe){
                System.out.println("String de nome vazia");
            }

            try{
                if(d.getDescription().contains(txtPesquisarChaveSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            catch(NullPointerException npe){
                System.out.println("String de descricao vazia");
            }
            /*
            try{
                if(d.isGluten() == jCheckBox1.isSelected()){
                    
                }
            }
            */
            try{
                if(d.getType().equalsIgnoreCase(txtPesquisarTipoSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            catch(NullPointerException npe){
                System.out.println("String de tipo vazia");
            }

            try{
                if(d.getDiscount() == Float.parseFloat(txtPesquisarDescontoSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            catch(NumberFormatException npe){
                System.out.println("String de desconto vazia");
            }

            try{
                if(d.getPrice() == Float.parseFloat(txtPesquisarPrecoSearch.getText())) {
                    temp.addElement("</li></ul></html>"+"<html><ul>"+d.getName()+"<li><b>Preco: </b>"+Float.toString(d.getPrice())+"</li><li><b>Descricao: </b>"+d.getDescription()+"</li></ul></html>");
                }
            }
            catch(NumberFormatException npe){
                System.out.println("String de preco vazia");
            }

        }
        this.setVisible(false);
    }//GEN-LAST:event_btnPesquisarSearchActionPerformed

    public DefaultListModel getList(){
        return temp;
    }
    
    private void txtPesquisarNomeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarNomeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarNomeSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblPesquisarAtributosSearch;
    private javax.swing.JLabel lblPesquisarChaveSearch;
    private javax.swing.JLabel lblPesquisarDescontoSearch;
    private javax.swing.JLabel lblPesquisarNomeSearch;
    private javax.swing.JLabel lblPesquisarPrecoSearch;
    private javax.swing.JLabel lblPesquisarTipoSearch;
    private javax.swing.JTextField txtPesquisarChaveSearch;
    private javax.swing.JTextField txtPesquisarDescontoSearch;
    private javax.swing.JTextField txtPesquisarNomeSearch;
    private javax.swing.JTextField txtPesquisarPrecoSearch;
    private javax.swing.JTextField txtPesquisarTipoSearch;
    // End of variables declaration//GEN-END:variables
}
