/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg42client.GUI;

import Data.Dish;

/**
 *
 * @author andre
 */
public class AddDishJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddDishJFrame
     */
    public AddDishJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxVegetarianoAddDish = new javax.swing.JCheckBox();
        cboxVeganoAddDish = new javax.swing.JCheckBox();
        cboxGlutenAddDish = new javax.swing.JCheckBox();
        cboxLactoseAddDish = new javax.swing.JCheckBox();
        txtNomeAddDish = new javax.swing.JTextField();
        lblNomeAddDish = new javax.swing.JLabel();
        lblDescricaoAddDish = new javax.swing.JLabel();
        lblPrecoAddDish = new javax.swing.JLabel();
        btnEnviarAddDish = new javax.swing.JButton();
        lblAddDish = new javax.swing.JLabel();
        jspAddDish = new javax.swing.JScrollPane();
        txtDescricaoAddDish = new javax.swing.JTextArea();
        txtPrecoAddDish = new javax.swing.JFormattedTextField();
        lblTipoAddDish = new javax.swing.JLabel();
        txtTipoAddDish = new javax.swing.JTextField();
        lblDescontoAddDish = new javax.swing.JLabel();
        txtDescontoAddDish = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        cboxVegetarianoAddDish.setText("Vegetariano");

        cboxVeganoAddDish.setText("Vegano");

        cboxGlutenAddDish.setText("Glúten");

        cboxLactoseAddDish.setText("Lactose");

        txtNomeAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAddDishActionPerformed(evt);
            }
        });

        lblNomeAddDish.setText("Nome:");

        lblDescricaoAddDish.setText("Descrição:");

        lblPrecoAddDish.setText("Preço:");

        btnEnviarAddDish.setText("Enviar");
        btnEnviarAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarAddDishActionPerformed(evt);
            }
        });

        lblAddDish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAddDish.setText("Adicionar Prato");

        txtDescricaoAddDish.setColumns(20);
        txtDescricaoAddDish.setRows(5);
        jspAddDish.setViewportView(txtDescricaoAddDish);

        txtPrecoAddDish.setToolTipText("Preço do produto");
        txtPrecoAddDish.setSelectionColor(new java.awt.Color(102, 153, 255));
        txtPrecoAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoAddDishActionPerformed(evt);
            }
        });

        lblTipoAddDish.setText("Tipo:");

        txtTipoAddDish.setToolTipText("Tipo do produto");

        lblDescontoAddDish.setText("Desconto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoAddDish)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jspAddDish)
                        .addComponent(txtNomeAddDish)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEnviarAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNomeAddDish)
                                .addComponent(lblAddDish)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cboxGlutenAddDish)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboxVeganoAddDish)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboxVegetarianoAddDish)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboxLactoseAddDish))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTipoAddDish)
                                            .addGap(85, 85, 85))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtTipoAddDish)
                                            .addGap(21, 21, 21)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescontoAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDescontoAddDish))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPrecoAddDish)
                                        .addComponent(txtPrecoAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(10, 10, 10))))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddDish)
                .addGap(21, 21, 21)
                .addComponent(lblNomeAddDish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescricaoAddDish)
                .addGap(2, 2, 2)
                .addComponent(jspAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxGlutenAddDish)
                    .addComponent(cboxVeganoAddDish)
                    .addComponent(cboxVegetarianoAddDish)
                    .addComponent(cboxLactoseAddDish))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoAddDish)
                    .addComponent(lblDescontoAddDish)
                    .addComponent(lblPrecoAddDish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescontoAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnEnviarAddDish)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAddDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAddDishActionPerformed

    private void btnEnviarAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarAddDishActionPerformed
        
        Dish dish = new Dish(txtNomeAddDish.getText(),
                            txtDescricaoAddDish.getText(),
                            cboxGlutenAddDish.isSelected(),
                            cboxVeganoAddDish.isSelected(),
                            cboxVegetarianoAddDish.isSelected(),
                            cboxLactoseAddDish.isSelected(),
                            txtTipoAddDish.getText(),
                            Float.parseFloat(txtDescontoAddDish.getText()),
                            Float.parseFloat(txtPrecoAddDish.getText())
                            );
        dish.sendDish();
               
    }//GEN-LAST:event_btnEnviarAddDishActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void txtPrecoAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoAddDishActionPerformed
        
    }//GEN-LAST:event_txtPrecoAddDishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDishJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarAddDish;
    private javax.swing.JCheckBox cboxGlutenAddDish;
    private javax.swing.JCheckBox cboxLactoseAddDish;
    private javax.swing.JCheckBox cboxVeganoAddDish;
    private javax.swing.JCheckBox cboxVegetarianoAddDish;
    private javax.swing.JScrollPane jspAddDish;
    private javax.swing.JLabel lblAddDish;
    private javax.swing.JLabel lblDescontoAddDish;
    private javax.swing.JLabel lblDescricaoAddDish;
    private javax.swing.JLabel lblNomeAddDish;
    private javax.swing.JLabel lblPrecoAddDish;
    private javax.swing.JLabel lblTipoAddDish;
    private javax.swing.JTextField txtDescontoAddDish;
    private javax.swing.JTextArea txtDescricaoAddDish;
    private javax.swing.JTextField txtNomeAddDish;
    private javax.swing.JFormattedTextField txtPrecoAddDish;
    private javax.swing.JTextField txtTipoAddDish;
    // End of variables declaration//GEN-END:variables
}
