/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg42client.GUI;

/**
 *
 * @author Bhárbara
 */
public class DeleteDishJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteDishJFrame
     */
    public DeleteDishJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExcluirPratoDeleteDish = new javax.swing.JLabel();
        txtExcluirPratoDeleteDish = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPratoExcluidoDeleteDish = new javax.swing.JTextArea();
        btnExcluirDeleteDish = new javax.swing.JButton();
        lblPratoExcluidoDeleteDish = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblExcluirPratoDeleteDish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblExcluirPratoDeleteDish.setText("Excluir Prato");

        txtPratoExcluidoDeleteDish.setColumns(20);
        txtPratoExcluidoDeleteDish.setRows(5);
        jScrollPane1.setViewportView(txtPratoExcluidoDeleteDish);

        btnExcluirDeleteDish.setText("Excluir");
        btnExcluirDeleteDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDeleteDishActionPerformed(evt);
            }
        });

        lblPratoExcluidoDeleteDish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPratoExcluidoDeleteDish.setText("Prato Excluído");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPratoExcluidoDeleteDish)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblExcluirPratoDeleteDish)
                        .addComponent(txtExcluirPratoDeleteDish)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addComponent(btnExcluirDeleteDish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExcluirPratoDeleteDish)
                .addGap(18, 18, 18)
                .addComponent(txtExcluirPratoDeleteDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirDeleteDish)
                .addGap(18, 18, 18)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPratoExcluidoDeleteDish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirDeleteDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDeleteDishActionPerformed
        String dish_name = txtExcluirPratoDeleteDish.getText();
        
    }//GEN-LAST:event_btnExcluirDeleteDishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDishJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirDeleteDish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblExcluirPratoDeleteDish;
    private javax.swing.JLabel lblPratoExcluidoDeleteDish;
    private javax.swing.JTextField txtExcluirPratoDeleteDish;
    private javax.swing.JTextArea txtPratoExcluidoDeleteDish;
    // End of variables declaration//GEN-END:variables
}
